version: '3.8'
services:
  node:
    container_name: nodeMKS
    restart: always
    build: ./server
    ports:
      - '3000:3000'
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
  db:
    container_name: postgresMKS
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - TZ=America/Sao_Paulo
    ports:
      - '5440:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    container_name: redisMKS
    image: redis
    command: redis-server --requirepass 1234 --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/duducp/Redis:/var/lib/postgresql/data
volumes:
  db:
    driver: local